/*********************************************************************************************************************************************************************
@description  Controller para Teste de Consulta de Ofertas.
@author Diogo Borges - Avanxo
@date 30/12/2019
@Classe criada por conta da história PLV-3223       
**********************************************************************************************************************************************************************/
@isTest 
public class CtrConsultaOfertasTest {
    // @isTest 
	// static void testUnit() {	
	// 	Test.StartTest(); 
	// 		CtrConsultaOfertas controller = new CtrConsultaOfertas();
	// 		controller.consultar();
	// 	Test.StopTest();
	// }
}