/**
 * Expurgo de dados para o Orçamento
 *  objeto: AttachedContentDocuments
 * caminho do objeto:
 * AttachedContentDocuments 
 *  > Opportunity
 * 
 * 09/02/2024
 */
public with sharing class ExpurgoAttachedContentDocuments {
    /**
     * Buscar dados
     */
    public List<Object> getDadosExpurgo(Integer qt) {
        List<Object> expList= new List<Object>();

        return expList;
    }
    /**
     * Excluir dados
     */
    public void deleteDadosExpurgo(List<Object> expList) {

    }
}