/****************************************************************************************************************************
 * Classe de Negocio para tratar todo o processo de Renovação                                                               *
 * @author : Globant                                                                                                        *
 * @date 27/05/2022                                                                                                         *
 * Classe implementada tendo como origem a história RVI-118                                                                 *
 * **************************************************************************************************************************/
public class RenovacoesBO {
	private static final RenovacoesBO instancia = new RenovacoesBO();
    
    public static RenovacoesBO getInstance(){
        return instancia;
    }
}