@isTest
private class SolicitarPgtoCasoFilhoCtrTOTest {

    @isTest
    static void SolicitarPgtoCasoFilhoCtrTOTest() {

        Test.startTest();

        SolicitarPagamentoCasoFilhoControllerTO spcfcTO = new SolicitarPagamentoCasoFilhoControllerTO();
        SolicitarPagamentoCasoFilhoControllerTO.RetornoTO retornoTO = new SolicitarPagamentoCasoFilhoControllerTO.RetornoTO();
        retornoTO.Id = 'teste';

        Test.stopTest();
    }
}